### ISSUE TITLE
Impossible to print using the embedded

### ISSUE THREAD

**Issue by nikku** [presenta-software/presenta-lib-starterkit#1]
After giving a talk I wanted to print it, however I do not find any configuration that prints slides full-page:

![image](https://user-images.githubusercontent.com/58601/103776830-4fa81580-5030-11eb-8b11-f82cbb6ba424.png)

Changing the format to A4 or letter even prints each slide on two pages: 

![image](https://user-images.githubusercontent.com/58601/103777129-b75e6080-5030-11eb-9205-c46a33fb6968.png)

I tried to dive into the printer page and investigate what causes that wierd alignment when printing to PDF (in Chrome) but failed.

Do you have any pointers? Any specific format I should use to print properly?

**Comment by abusedmedia** [comment]
Hi @nikku 

There was a wrong setting in the CSS, I wasn't able to print correctly like you mentioned. 
Now I can print using a custom format in the printer dialog of 237 x 135 mm.
Let me know if it solves the issue.

**Comment by nikku** [comment]
Thanks! Works much better.
