### ISSUE TITLE
All pages are blank except the first one, when printing from firefox

### ISSUE THREAD

**Issue by cyberic99** [presenta-software/presenta-lib-starterkit#2]
Here are 2 PDFs of the example presentation.md, 'printed' from firefox and chromium

[PRESENTA Lib Printable_chromium.pdf](https://github.com/presenta-software/presenta-lib-starterkit/files/6644607/PRESENTA.Lib.Printable_chromium.pdf)
[PRESENTA Lib Printable_firefox.pdf](https://github.com/presenta-software/presenta-lib-starterkit/files/6644608/PRESENTA.Lib.Printable_firefox.pdf)

You can see that when printing from firefox, only the first page is displayed the other ones are blank
(and in the print preview too)

This is on Archlinux.
Firefox: 89.0
Chromium: Version 91.0.4472.77 (Official Build) Arch Linux (64-bit)

Thank you

**Comment by abusedmedia** [comment]
Hi @cyberic99 

Thanks for reporting the issue.
You're right, on Firefox, for some reason, the printer considers just the first page.
In the meantime of a fix (it's not that easy debugging the browser printer), I've found a workaround for it:

Add this CSS rule in the style tag of the `printer.html` file:
```css
.ff_fix{
   width:100%;
   min-height: 1px;
}
```

and this code after this [line number](https://github.com/presenta-software/presenta-lib-starterkit/blob/3a0b4c4dfbed13e596f4f14757dd693aeb678b36/printer.html#L77):
```js
wrapper.innerHTML = '<div class="ff_fix"></div>'
```
